package lab.pongoauth.boundary.repository;

import io.vertx.core.AsyncResult;
import io.vertx.core.Future;
import io.vertx.core.Handler;
import io.vertx.core.json.JsonObject;
import io.vertx.ext.mongo.MongoClient;

import java.util.ArrayList;
import java.util.List;

import com.mongodb.MongoWriteException;

import lab.pongoauth.entity.Message;

public class MongoMessageRepository implements MessageRepository {

  private final MongoClient mongoClient;

  public MongoMessageRepository(final MongoClient mongoClient) {
    this.mongoClient = mongoClient;
  }

  @Override
  public void save(final Message message, final Handler<AsyncResult<Message>> asyncResultHandler) {

    JsonObject document = new JsonObject();
    document.put("text", message.getText());

    if (message.getId() != null) {
      document.put("_id", message.getId());
      
    }

    mongoClient.insert("messages", document, res -> {
      if (res.succeeded()) {
        String autoGeneratedId = res.result();
        if (autoGeneratedId == null ){
          asyncResultHandler.handle(Future.succeededFuture(new Message(message.getId()).setText(message.getText())));
        } else {
          asyncResultHandler.handle(Future.succeededFuture(new Message(autoGeneratedId).setText(message.getText())));
        }
      } else {
        if (res.cause() instanceof MongoWriteException && res.cause().getMessage().contains("E11000 duplicate key error collection")){
          DuplicateMessageException exception = new DuplicateMessageException("Already exists a message with the provided id.",res.cause());
          asyncResultHandler.handle(Future.failedFuture(exception));
        } else {
          asyncResultHandler.handle(Future.failedFuture(res.cause()));
        }
      }
    });
  }

  @Override
  public void listAll(Handler<AsyncResult<List<Message>>> asyncResultHandler) {
    JsonObject query = new JsonObject();
    List<Message> messages = new ArrayList<>();
    mongoClient.find("messages", query, res -> {
      if (res.succeeded()) {
        for (JsonObject json : res.result()) {
          messages.add(Message.createFromJsonString(json.toString()));
        }
        asyncResultHandler.handle(Future.succeededFuture(messages));
      } else {
        asyncResultHandler.handle(Future.failedFuture(res.cause()));
      }
    });
  }
}
