package lab.pongoauth.boundary.repository;

import io.vertx.codegen.annotations.Nullable;
import io.vertx.core.AsyncResult;
import io.vertx.core.Future;
import io.vertx.core.Handler;
import io.vertx.core.json.JsonObject;
import io.vertx.ext.mongo.MongoClient;
import io.vertx.ext.mongo.WriteOption;

import java.util.logging.Level;
import java.util.logging.Logger;

import com.mongodb.MongoWriteException;

import lab.pongoauth.entity.Message;

public class MongoMessageRepository implements MessageRepository {

  private static final String TAG = MongoMessageRepository.class.getName();
  private static final Logger LOGGER = Logger.getLogger(TAG);

  private final MongoClient mongoClient;

  public MongoMessageRepository(final MongoClient mongoClient) {
    this.mongoClient = mongoClient;
  }

  @Override
  public void save(final Message message, final Handler<AsyncResult<Message>> asyncResultHandler) {

    JsonObject document = new JsonObject();
    document.put("text", message.getText());

    if (message.getId() != null) {
      document.put("_id", message.getId());
      
    }

    mongoClient.insert("messages", document, res -> {
      if (res.succeeded()) {
        String autoGeneratedId = res.result();
        if (autoGeneratedId == null ){
          asyncResultHandler.handle(Future.succeededFuture(new Message(message.getId()).setText(message.getText())));
        } else {
          asyncResultHandler.handle(Future.succeededFuture(new Message(autoGeneratedId).setText(message.getText())));
        }
      } else {
        LOGGER.log(Level.WARNING, "Failed to save message: " + document, res.cause());
        if (res.cause() instanceof MongoWriteException && res.cause().getMessage().contains("E11000 duplicate key error collection")){
          DuplicateMessageException exception = new DuplicateMessageException("Already exists a message with the provided id.",res.cause());
          asyncResultHandler.handle(Future.failedFuture(exception));
        } else {
          asyncResultHandler.handle(Future.failedFuture(res.cause()));
        }
      }
    });
  }
}
