version: '3'
services:
  mongodb:
    image: mongo:3.1
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
  rabbitmq:
    image: rabbitmq:3.7.8
    ports:
      - "5672:5672"
  test:
    build:
      context: ./
      dockerfile: Dockerfile-test
    command: "mvn test"
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - rabbitmq
